[lightgbm]
n_estimators = 2000
learning_rate = 0.03
num_leaves = 63
reg_alpha = 0.10
reg_lambda = 0.20
subsample = 0.85
colsample_bytree = 0.85
random_state = 42

[features]

[monotone]
enabled = true

[training]
min_rows_for_es = 500
early_stop_rounds = 120

[calibration]
enabled = true
ridge_lambda = 4.0
raw_slope_bounds = [0.5, 1.2]
use_form = true
min_val_rows = 100

[priors]
# MID/FWD
form_boost_midfwd = 1
att_boost_midfwd = 0.30
att_boost_use_xgxa = true

# DEF/GK
cs_penalty_defgk = 0.45
cs_cap = 1.2
defgk_tough_penalty = 0.70
tough_threshold = 4

[scalers]
fallback_center = 1.0
global_multiplier = 1.00
hard_cap = 0
clip_zero = true
pre_clip_zero = true

[scalers.temperature]
default = 0.90
GK = 0.95
DEF = 0.92
MID = 0.88
FWD = 0.88

[scalers.high_end_compression]
quantile = 0.75
slope = 0.60

[scalers.mean_align]
enabled = false
# target = 1.2  # if you want to force-align means per position

[quantile_mapping]
enabled = false
n_quantiles = 9
blend_weight = 0.5
min_val_rows = 200

[explanations]
top_k = 5
print_samples = true
samples = 5
