---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Create TFBACUP Folder
    ansible.builtin.file:
      path: "/home/TF_FILES"
      state: directory

  - name: Copy Terraform Folder
    copy:
      src: "../../k8-cluster/"
      dest: /home/TF_FILES/
      owner: ubuntu
      group: ubuntu
      mode: '777'
  
  - name: Clean up terraform folder
    file:
      path: ../../{{ inventory_hostname }}/
      state: absent
    delegate_to: localhost

  - name: Change hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Install docker
    import_tasks: install-docker.yml
    become: yes

  - name: Enable Root Login
    lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^PermitRootLogin'
          line: "PermitRootLogin yes"
          state: present
          backup: yes
    become: yes

  - name: Copy SSH Key for root
    copy:
      src: ~/.ssh/id_ecdsa.pub
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0600'
    become: yes
    
  - name: Reboot VM
    reboot: