# jenkins-values.yaml
controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17
    pullPolicy: IfNotPresent

  nodeSelector:
    kubernetes.io/hostname: "k8-node2"

  resources:
    requests: { cpu: "100m", memory: "500Mi" }
    limits:   { cpu: "1",    memory: "2Gi"    }

  admin:
    username: "admin"
    password: "tempPassword"

  serviceType: NodePort
  nodePort: 32080

  runAsUser: 1000
  fsGroup: 1000
  runAsGroup: 1000

persistence:
  enabled: true
  existingClaim: "jenkins-pvc"
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

tests:
  enabled: false
