apiVersion: batch/v1
kind: CronJob
metadata:
  name: fpl-weekly
  labels:
    app: etl-jobs
spec:
  schedule: "0 3 * * 1"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 1800
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: etl-jobs
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: tmp
              emptyDir: {}
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 2Gi
            - name: fpl-data
              persistentVolumeClaim:
                claimName: fpl-data-pvc
          initContainers:
            - name: wait-for-postgres
              image: postgres:17-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_HOST
                  value: "postgres"
                - name: DB_PORT
                  value: "5432"
              command: ["sh", "-c"]
              args: |
                echo "Waiting for Postgres at ${DB_HOST}:${DB_PORT} ..."
                until pg_isready -h "${DB_HOST}" -p "${DB_PORT}"; do
                  sleep 3
                done
                echo "Postgres is ready."
            - name: seed-current-data
              image: ghcr.io/tamhid92/fpl:staging
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh","-lc"]
              args: |
                set -euo pipefail
                mkdir -p /data
                # Seed only once
                if [ ! -f /data/current_data.csv ]; then
                  if [ -f /app/data/current_data.csv ]; then
                    cp /app/data/current_data.csv /data/current_data.csv
                  else
                    # If you ever ship without a seed, initialize with header-only or empty file
                    : > /data/current_data.csv
                  fi
                  chown 10001:10001 /data/current_data.csv
                fi
              volumeMounts:
                - name: fpl-data
                  mountPath: /data
          containers:
            - name: etl
              image: ghcr.io/tamhid92/fpl:staging
              imagePullPolicy: Always
              command: ["/bin/sh","-lc"]
              args: ["exec python /app/entrypoint.py update"]
              env:
                - name: DB_HOST
                  value: "postgres"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: DB_NAME
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: DB_SUPERUSER
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secrets
                      key: POSTGRES_PASSWORD
                - name: API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: api-auth
                      key: API_TOKEN
                - name: DATA_DIR
                  value: "/data"
                - name: TMP_DIR
                  value: "/tmp"
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "2"
                  memory: "3Gi"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: dshm
                  mountPath: /dev/shm
                - name: fpl-data
                  mountPath: /data
