name: Trigger Jenkins Job to push Prediction Data to DB

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: [self-hosted, k8s]

    env:
      JENKINS_URL:  http://jenkins.jenkins.svc.cluster.local:8080
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      JENKINS_JOB:  upload_preds_to_db

    steps:
      - name: Trigger Jenkins
        shell: bash
        run: |
          set -euo pipefail

          # Try to get CSRF crumb (works whether CSRF is enabled or not)
          CRUMB_JSON="$(curl -sf --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
            "${JENKINS_URL}/crumbIssuer/api/json" || true)"

          if [[ -n "${CRUMB_JSON}" ]]; then
            CRUMB="$(printf '%s' "${CRUMB_JSON}" | sed -n 's/.*"crumb":"\([^"]*\)".*/\1/p')"
            EXTRA=(-H "Jenkins-Crumb:${CRUMB}")
          else
            EXTRA=()
          fi

          BUILD_URL="${JENKINS_URL}/job/${JENKINS_JOB}/build"

          # Trigger build and capture HTTP status
          HTTP_CODE=$(curl -sS -o /dev/null -w "%{http_code}" \
            -X POST --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
            "${EXTRA[@]}" "${BUILD_URL}")

          # Jenkins typically returns 201 (Created). Some setups may 302.
          if [[ "${HTTP_CODE}" != "201" && "${HTTP_CODE}" != "302" ]]; then
            echo "Unexpected HTTP status from Jenkins: ${HTTP_CODE}"
            exit 1
          fi

          echo "Triggered Jenkins job '${JENKINS_JOB}' (HTTP ${HTTP_CODE})"
